const PIXELART_SCALE_FACTOR = 1.5;

const TERRAIN_SCALE_FACTOR = 1;

const ENEMY_SPAWN_PROBABILITY = 0.05; // 0.05 is "normal"  value

const CHARACTER_STATES = {
  DEAD: 'dead',
  DYING: 'dying',
  IDLE: 'idle',
  MOVING: 'moving'
};

const ANIMATION_SLOWDOWN = 5;

const ENEMY_SENSE_DISTANCE = 100; //Infinity;

const ENEMY_SPAWN_MIN_DISTANCE = 80;

const ENEMY_EXPLOSION_DISTANCE = 10;

const ENEMY_INITIAL_COUNT = 1;

const PROJECTILE_ROTATION = Math.PI / 2;

const PROJECTILE_DAMAGE = 50;

const PROJECTILE_SPEED = 200;

const PROJECTILE_MAX_DISTANCE = 200;
